config/routes.rb
Rails.application.routes.draw do
  resources :expeditions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/equipment.rb
class Equipment < ApplicationRecord
    has_many :expedition_equipments
    has_many :expeditions, through: :expedition_equipments

    validates :name, presence: :true
end

app/models/expedition.rb
class Expedition < ApplicationRecord
    has_many :expedition_equipments
    has_many :equipment, through: :expedition_equipments

    def equipment=(equipment)
        equipment.each do |item|
            if !item[:name].empty?
                if new_item = Equipment.find_by(name: item[:name])
                    self.equipment << new_item
                else
                    self.equipment.build(name: item[:name])
                end
            end
        end
    end
end

app/models/expedition_equipment.rb
class ExpeditionEquipment < ApplicationRecord
  belongs_to :expedition
  belongs_to :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expeditions_controller.rb
class ExpeditionsController < ApplicationController

    def index
        @expeditions = Expedition.all
    end

    def new
        @expedition = Expedition.new
    end

    def create
        @expedition = Expedition.new(expedition_params)
        if @expedition.save
            redirect_to expeditions_path
        else
            render :new
        end
    end

    private

        def expedition_params
            params.require(:expedition).permit(:name, :description, :length, :difficulty, equipment: [:name])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expeditions/index.html.erb
<h1>All My Expeditions</h1>

<%= link_to "Create New Expedition", new_expedition_path %>

<% @expeditions.each do |expedition| %>
    <div>
        <h3><%= expedition.name %></h3>
        <p><%= expedition.description %></p>
        <p>Length: <%= expedition.length %> KM</p>
        <p>Difficulty: <%= expedition.difficulty %></p>
        <% if expedition.equipment.count > 0 %>
            <p>Required Equipment</p>
            <ul>
                <% expedition.equipment.each do |equipment| %>
                    <li><%= equipment.name %></li>
                <% end %>
            </ul>
        <% end %>
    </div>
<% end %>

app/views/expeditions/new.html.erb
<h2>New Expedition Form</h2>

<form action="/expeditions" method="POST">
    <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
    <div>
        <label for="expedition_name">Name</label>
        <div>
            <input type="text" name="expedition[name]" value="<%= @expedition.name %>" placeholder="Name" />
        </div>
    </div>
    <div>
        <label for="expedition_description">Description</label>
        <div>
            <textarea name="expedition[description]" placeholder="Description"><%= @expedition.description %></textarea>
        </div>
    </div>
    <div>
        <label for="expedition_length">Length</label>
        <div>
            <input type="number" placeholder="1.55" step="0.01" name="expedition[length]" value="<%= @expedition.length %>" />
        </div>
    </div>
    <div>
        <label for="expedition_difficulty">Difficulty</label>
        <div>
            <input name="expedition[difficulty]" placeholder="Easy" value="<%= @expedition.difficulty %>" />
        </div>
    </div>
    <div>
        <label for="expedition_equipment">Required Equipment</label>
        <% 5.times.each do %>
            <div>
                <input name="expedition[equipment][][name]" placeholder="Equipment Name" />
            </div>
        <% end %>
    </div>
    <input type="submit" value="Create Expedition" />
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpeditionMaker2017</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>